* paradox

** Unexpected hanging paradox
A judge tells a condemned prisoner that he will be hanged at noon on one weekday in the following week but that the execution will be a surprise to the prisoner. He will not know the day of the hanging until the executioner knocks on his cell door at noon that day.

Having reflected on his sentence, the prisoner draws the conclusion that he will escape from the hanging. His reasoning is in several parts. He begins by concluding that the "surprise hanging" can't be on Friday, as if he hasn't been hanged by Thursday, there is only one day left – and so it won't be a surprise if he's hanged on Friday. Since the judge's sentence stipulated that the hanging would be a surprise to him, he concludes it cannot occur on Friday.

He then reasons that the surprise hanging cannot be on Thursday either, because Friday has already been eliminated and if he hasn't been hanged by Wednesday noon, the hanging must occur on Thursday, making a Thursday hanging not a surprise either. By similar reasoning, he concludes that the hanging can also not occur on Wednesday, Tuesday or Monday. Joyfully he retires to his cell confident that the hanging will not occur at all.

The next week, the executioner knocks on the prisoner's door at noon on Wednesday – which, despite all the above, was an utter surprise to him. Everything the judge said came true.

** super task
considered a lamp that may either be on or off. At time t = 0 the lamp is off, and the switch is flipped on at t = 1/2; after that, the switch is flipped after waiting for half the time as before. Thomson asks what is the state at t = 1. 

** Olbers' paradox 
Olbers' paradox describes the contradiction between the dark night sky and the assumption of a static, infinite, and eternal universe filled with countless stars.

** Boltzmann brain
Over a sufficiently long time, random fluctuations could cause particles to spontaneously form literally any structure of any degree of complexity, including a functioning human brain.

** Fermi paradox
The Fermi paradox is the conflict between the high probability of advanced extraterrestrial civilizations existing and the lack of any evidence or observable activity of such civilizations.

** Norton's dome
https://en.wikipedia.org/wiki/Norton%27s_dome


