* puzzle index

** nim game
The game begins with a number of piles, each containing a certain number of objects. 
The players take turns choosing one of the piles and removing any number of objects from it, from a single object to the entire pile.
A player must take at least one object on their turn.  The player who takes the last object wins.

** Wythoff's Game
This game is played with two piles of stones. Players can either remove any number of stones from a single pile (like in Nim) or remove the same number of stones from both piles.

** Numbered Hats
A warden places a hat on the head of each of 100 prisoners, each with a random number from 1 to 100. There may be duplicates. Each prisoner can see everybody's hat but their own. Each prisoner then guesses their own number; if any guess correctly, they all go free. The group may not communicate in any way during the trial, but may strategize beforehand. What strategy has the best chance of success?

** Colored Hats
A warden lines up a group of 30 prisoners so they can see everybody in front of them and nobody behind them, then places either a red or a blue hat on each of their heads, randomly. He then goes from the back of the line to the front, telling each prisoner to guess the color of their own hat. Each who guesses correctly is freed. The prisoners cannot see the color of their own hat, and cannot communicate with each other, but can hear each others' guesses and can strategize beforehand. What strategy saves the greatest number of prisoners?

** Coins on a Chessboard
A warden takes prisoner A into a room containing a chessboard, on each square of which is a coin randomly showing heads or tails. He then indicates a random square on that board. Prisoner A is given the chance to flip one coin (or none), then taken from the room, after which prisoner B is taken into the room and must say which square the warden indicated. The two prisoners may strategize beforehand, but may not communicate during the trial (except with the single coin flip). What should be their strategy?

** Seven Puzzles You Think You Must Not Have Heard Correctly
https://news.ycombinator.com/item?id=12380879
** Names in Boxes
The names of 100 prisoners are placed in 100 wooden boxes, one name to a box, and the boxes are
lined up on a table in a room. One by one, the prisoners are led into the room; each may look
in at most 50 boxes, but must leave the room exactly as he found it and is permitted no further
communication with the others.
The prisoners have a chance to plot their strategy in advance, and they are going to need it,
because unless every single prisoner finds his own name all will subsequently be executed.
Find a strategy for them which which has probability of success exceeding 30%.

** Boxes in Boxes
At many train stations, post offices and currier services around the world, the cost of sending a
rectangular box is determined by the sum of its dimensions; that is, length plus width plus height.
Prove that you can’t “cheat” by packing a box into a cheaper box.

** Love in Kleptopia
Jan and Maria have fallen in love (via the internet) and Jan wishes to mail her a ring. Unfortunately,
they live in the country of Kleptopia where anything sent through the mail will be stolen unless it
is enclosed in a padlocked box. Jan and Maria each have plenty of padlocks, but none to which the
other has a key. How can Jan get the ring safely into Maria’s hands?

** The Random Native
The logician of Martin Gardner’s first Scientific American collection is again visiting the South
Seas, and is as before at a fork, wanting to know which of two roads leads to the village. This
time, present are three willing natives, one each from a tribe of invariable truth-tellers, a tribe of
invariable liars, and a tribe of random answerers. Of course the logician doesn’t know which native
is from which tribe. Moreover, he is permitted to ask only two yes-or-no questions, each question
being directed to just one native. Can he get the information he needs?

In Martin Gardner’s columns it was pointed out that in the original one-native problem, the
logician can get to the village even if he has forgotten which of the native words (“pish” and “tush”)
means “yes” and which means “no.” 

** prisoners and lamp
There are 100 prisoners. At random times one prisoner is chosen uniformly at random and led into a room with a single lamp. The prisoner can choose to switch it on or off or leave it as the last visiting prisoner left it. Apart from the state of the lamp he must leave the room unchanged.

After visiting the room, each prisoner is asked if every prisoner has visited the room by now. If he answers 'Yes' and indeed everyone has been to the room at least once, then everybody is freed immediately. Otherwise they are all executed ;) He can answer 'I don't know' without any consequences.

Apart from the lamp being on or off the prisoners have no way of communication at all, but of course as is customary in such puzzles they can plot a strategy in advance and everybody is a perfect logician.

So, to clarify: The goal is for one prisoner to be 100% sure that everybody has been to the room at least once. The "easiest" solution would simply be to wait a few billion years (it's an abstract puzzle, they are all immortal anyways ;). But of course there is a more elegant solution that terminates earlier.
